server:
  port: 8762
  
spring: 
  application: 
    name: config-server
    
  cloud:
    config: 
      server: 
        native:
          search-locations: D:\\Best Sample Project\\dev-project\\workspaces\\spring-boot-microservice\\config
 
  profiles: 
    active: native  
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka   
